plugin:
    name: 'bsbvolmachten.contentblocks::lang.plugin.name'
    description: 'bsbvolmachten.contentblocks::lang.plugin.description'
    author: 'BSB Volmachten'
    icon: oc-icon-align-justify
    homepage: ''
permissions:
    manage-blocks:
        tab: 'Content Blokkken Beheren'
        label: 'Content Blokkken Beheren'
navigation:
    main-menu-item:
        label: Blokken
        url: bsbvolmachten/contentblocks/fullblocks
        icon: icon-align-justify
        permissions:
            - manage-blocks
        sideMenu:
            side-menu-item:
                label: 'Volledige breedte'
                url: bsbvolmachten/contentblocks/fullblocks
                icon: icon-square
                permissions:
                    - manage-blocks
