name: Fullblocks
modelClass: BsbVolmachten\ContentBlocks\Models\Fullblocks
form: $/bsbvolmachten/contentblocks/models/fullblocks/fields.yaml
defaultRedirect: bsbvolmachten/contentblocks/fullblocks
create:
    title: 'Blok Aanmaken'
    redirect: 'bsbvolmachten/contentblocks/fullblocks/update/:id'
    redirectClose: bsbvolmachten/contentblocks/fullblocks
    flashSave: 'Blok Opgeslagen'
update:
    title: 'Blok Bewerken'
    redirect: bsbvolmachten/contentblocks/fullblocks
    redirectClose: bsbvolmachten/contentblocks/fullblocks
    flashSave: 'Blok Opgeslagen'
    flashDelete: 'Blok Verwijderd'
preview:
    title: 'Blok Weergeven'
